all:
  children:
    cisco:
      hosts:
        R1:
          ansible_host: 192.168.8.221
        R2:
          ansible_host: 192.168.8.222
        R3:
          ansible_host: 192.168.8.223
        R4:
          ansible_host: 192.168.8.224
        R5:
          ansible_host: 192.168.8.225
        R6:
          ansible_host: 192.168.8.226
        R7:
          ansible_host: 192.168.8.227
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_user: ansible
        ansible_password: ansible
        ansible_become: true
        ansible_become_method: enable
